meta_product_name: "FreeMentors"
meta_title: "FreeMentors - Get prepared for your freelance journey"
meta_description: "The freelance market is a very competitive market where new freelancers are in direct competition with experienced / senior freelancers. FreeMentors
help you to find your first freelance assignment thanks to our community of mentor freelancers"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter Not activated now
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
